# Generated by Django 2.1.7 on 2019-03-13 10:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 13, 10, 44, 2, 911818, tzinfo=utc)),
        ),
    ]
