# Generated by Django 2.1.7 on 2019-03-13 10:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190313_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 13, 10, 53, 3, 182066, tzinfo=utc)),
        ),
    ]
