# Generated by Django 2.1.7 on 2019-03-13 11:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190313_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
